apiVersion: batch/v1
kind: Job
metadata:
  name: build-tenpointnine-image
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
    # Increase hook timeout to 20 minutes (adjust as needed)
    "helm.sh/hook-timeout": "1800s"
spec:
  # Make sure we give the job enough time to finish building the image
  activeDeadlineSeconds: 1800
  backoffLimit: 0
  template:
    spec:
      containers:
        - name: docker-builder
          image: docker:20.10  # Docker CLI image
          securityContext:
            privileged: true  # Allows Docker socket access
          command: ["/bin/sh", "-c"]
          args:
            - |
              set -x

              echo "Starting build process..."
              echo "Installing git..."
              apk add --no-cache git

              echo "Cloning repository..."
              git clone {{ .Values.repo.url }}

              cd {{ .Values.repo.name }}

              echo "Building Docker image {{ .Values.image.repository }}:{{ .Values.image.tag }}..."
              # Pipe docker build output to /dev/termination-log
              docker build --progress=plain -t {{ .Values.image.repository }}:{{ .Values.image.tag }} . 2>&1 | tee /dev/termination-log

              echo "Docker build completed successfully. Cleaning up..."
              cd ..
              rm -rf {{ .Values.repo.name }}

              echo "Build process completed."
          volumeMounts:
            - name: docker-sock
              mountPath: /var/run/docker.sock  # Mount the Docker socket
      restartPolicy: Never
      volumes:
        - name: docker-sock
          hostPath:
            path: /var/run/docker.sock  # Host Docker daemon
            type: Socket
